version: '3'

services:
  app:
    container_name: node-knex-poc
    build: .
    depends_on: 
      - db
  db:
    container_name: postgres-knex-poc
    image: postgres:13-alpine
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=knexpoc
      - POSTGRES_PASSWORD=knexpoc
      - POSTGRES_USER=knexpoc
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  db:
    driver: local
    